# Generated by Django 3.2.7 on 2021-09-16 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MediaUploadApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='books/covers'),
        ),
    ]
